[project]
name = "final-assets-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Flask==3.0.3",
    "Flask-SQLAlchemy==3.1.1",
    "Flask-Login==0.6.3",
    "Flask-WTF==1.2.1",
    "Flask-Mail==0.10.0",
    "Flask-Migrate==4.0.7",
    "SQLAlchemy==2.0.51",
    "openpyxl==3.1.2",
    "reportlab==4.1.0",
    "pandas==2.2.2",
    "requests==2.34.2",
    "python-dotenv==1.0.1",
    "APScheduler==3.11.3"
]

[tool.vercel]
entrypoint = "run:app"
